### ISSUE TITLE
PHP Error[2]: include(ParagonIE_Sodium_Compat.php): failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by ursuleacv** [paragonie/sodium_compat#105]
The class ParagonIE_Sodium_Compat cannot be found in cli mode, works fine in php-fpm.

Steps to reproduce:

Install Yii frameword 1.x

run composer require pusher/pusher-php-server

run some command

PHP 7.0.33
pusher-php-server 3.4.1

**Comment by paragonie-scott** [comment]
Okay, based on the error code you included in this issue:

> PHP Error[2]: include(ParagonIE_Sodium_Compat.php): failed to open stream: No such file or directory

I'm going to assume this is an upstream issue. We don't name our files that way internally.

Can you post a full stack trace? (Use three backticks before and after to format them.)

```
like so

:)
```

**Comment by paragonie-scott** [comment]
Okay, this is an interesting one.

* https://github.com/yiisoft/yii/blob/83a86bca722e438f2e402d1e1cd7a723d41da12a/framework/YiiBase.php#L442-L443
* https://github.com/yiisoft/yii/blob/83a86bca722e438f2e402d1e1cd7a723d41da12a/framework/YiiBase.php#L462-L463

Yii looks for `\` in the class name. If it's not found, it tries to include the file flatly. Which doesn't work.

The best workaround is to create a file called `ParagonIE_Sodium_Compat.php` that just does nothing:

```php
<?php
// NOP
```

This should prevent the behavior in Yii's autoloader from breaking your app. I also attempted to contribute an upstream patch to Yii, but there's no guarantee it will be accepted. (Yii 1 seems to be a dead project.)

**Comment by paragonie-scott** [comment]
Looks like that's actually irrelevant. Hmm.

This might be a problem best fixed in https://github.com/pusher/pusher-http-php

**Comment by paragonie-scott** [comment]
Looks like https://github.com/yiisoft/yii/issues/4272 is the core problem here.
