### ISSUE TITLE
unparsed constants in error messages

### ISSUE THREAD

**Issue by Graziel** [paragonie/sodium_compat#108]
https://github.com/paragonie/sodium_compat/blob/master/src/Compat.php#L356

```
throw new SodiumException('Nonce must be CRYPTO_AEAD_XCHACHA20POLY1305_NPUBBYTES long');
```

**Comment by paragonie-scott** [comment]
These aren't "unparsed". They're the names of Googleable constants.

**Comment by Graziel** [comment]
fiar enough but still had to search for value so maybe add it in bracets? ie "CRYPTO_AEAD_AES256GCM_NPUBBYTES (12)"

**Comment by paragonie-scott** [comment]
This is a polyfill. If I'm going to make the change here, it also has to land upstream in the PHP extension.
