### ISSUE TITLE
Preloading Issue

### ISSUE THREAD

**Issue by oojacoboo** [paragonie/sodium_compat#113]
[16-Dec-2019 22:22:24 UTC] PHP Warning:  Can't preload already declared class SodiumException in /srv/www/vendor/paragonie/sodium_compat/src/SodiumException.php on line 7

Any ideas.  It's just a warning, but it's annoying and the only one I get in our entire code base.

**Comment by paragonie-security** [comment]
Can you see if https://github.com/paragonie/sodium_compat/commit/0ed3206e9be4a161c07ec1e25380b9efe716d89c fixes the problem on your system?

**Comment by paragonie-security** [comment]
We haven't heard back in a month. I believe this is fixed. Please let us know if you're still encountering issues.

**Comment by oojacoboo** [comment]
Apologies, but we disabled preloading for now, as there were other issues.  Thanks for the patch though.  I look forward to checking it out when we get preloading re-enabled.

**Comment by oojacoboo** [comment]
Hey, got a second to test this out again and it's not resolved.  The preloader doesn't complain, but now normal application execution results in the class not found.
