### ISSUE TITLE
Class 'ParagonIE_Sodium_Core_Util' not found

### ISSUE THREAD

**Issue by oojacoboo** [paragonie/sodium_compat#116]
With preloading, I'm getting the following error

```
Class 'ParagonIE_Sodium_Core_Util' not found
```

It seems this lib is in dire need of being updated to PSR-4 compatibility.

**Comment by oojacoboo** [comment]
The issue is resolved by removing the `is_callable` conditional check at the top of the `autoload.php` file.  It seems that the preload process evaluates this as false, which actually makes sense I guess.

I'm unsure of what the implications are for removing this check.  I've removed it and everything seems to be working fine on our end.

**Comment by paragonie-security** [comment]
Removing that check will break PHP < 5.3.

**Comment by oojacoboo** [comment]
PHP 5.3 was EOL 5 years and 7 months ago.  Can a new version be released instead?

**Comment by oojacoboo** [comment]
I guess we have to fork this thing.  That's unfortunate.

**Comment by paragonie-security** [comment]
This is a polyfill. The PHP EOL does not apply to our polyfill projects.

See #117 which should fix the problem you're experiencing.

**Comment by paragonie-security** [comment]
`v1.13.0` contains the fix. Please update to this version and let me know if the trouble persists.

**Comment by oojacoboo** [comment]
Testing now - thanks for the fix
