### ISSUE TITLE
Issue in crypto_box_open function

### ISSUE THREAD

**Issue by khangrey** [paragonie/sodium_compat#123]
SodiumException : Invalid MAC
/vendor/paragonie/sodium_compat/src/Crypto.php:1058
/vendor/paragonie/sodium_compat/src/Crypto.php:672
/vendor/paragonie/sodium_compat/src/Compat.php:1260

**Comment by paragonie-security** [comment]
Are you still experiencing this issue?

**Comment by paragonie-security** [comment]
It's likely that this was fixed in  `v1.17.0` or `v1.17.1`, but if not, please let me know.
