### ISSUE TITLE
sodium_crypto_aead_xchacha20poly1305_ietf_encrypt doesn't take null as Argument 2

### ISSUE THREAD

**Issue by superpoincare** [paragonie/sodium_compat#125]
This probably doesn't happen if sodium is installed natively with PHP but sodium_compat is giving the error that the function needs argument 2 as not null.

**Comment by paragonie-security** [comment]
This is fixed in `v1.15.0`.

**Comment by superpoincare** [comment]
Thanks.

This is not giving an error now but using `null` doesn't decrypt.

**Comment by paragonie-security** [comment]
Given this code...

```php
<?php

if (!extension_loaded('sodium')) {
    exit;
}
$key = random_bytes(32);
$nonce = random_bytes(24);

$message = 'Pi day was a month ago and I suddenly crave pie.';

$ciphertext = sodium_crypto_aead_xchacha20poly1305_ietf_encrypt($message, '', $nonce, $key);
$c2 = sodium_crypto_aead_xchacha20poly1305_ietf_encrypt($message, NULL, $nonce, $key);

var_dump(
    bin2hex($ciphertext), bin2hex($c2)
);
```

...I get this output:

```
string(128) "8e2e220c7c917e7dc65fe2af6af246eb9c1b38be92a1a2ef15cf9bd8cfbe242f46934485e5f94706df06dcb75a88acf79a6e044fb929113c9e56c42899ff677a"
string(128) "8e2e220c7c917e7dc65fe2af6af246eb9c1b38be92a1a2ef15cf9bd8cfbe242f46934485e5f94706df06dcb75a88acf79a6e044fb929113c9e56c42899ff677a"
```

This tells me that `NULL` and `""` (empty string) are treated the same by ext/sodium. Does that solve the problem for you?

**Comment by paragonie-security** [comment]
Version `v1.5.3` contains the complete fix, and has a regression test added to prevent this from ever being reintroduced.

**Comment by superpoincare** [comment]
Yeah, I had a decrypt function and that decrypts well now. 

Great!
