### ISSUE TITLE
box.json omits autoload-php7.php

### ISSUE THREAD

**Issue by bafta-benj** [paragonie/sodium_compat#159]
The sodium-compat.phar file fails to load on PHP 7.2.34 giving this error:
`Warning: require_once(phar:///www/codebase/Ampletracks/lib/sodium-compat.phar/autoload-php7.php): failed to open stream: phar error: "autoload-php7.php" is not a file in phar "/www/codebase/Ampletracks/lib/sodium-compat.phar" in phar:///www/codebase/Ampletracks/lib/sodium-compat.phar/autoload.php on line 41
`
This occurs with any of the pre-built releases starting from [Version 1.13.0] and also if I build the latest myself from scratch running the build-phar.sh script.

Updating dist/box.json as follows fixes the problem:

```
diff --git a/dist/box.json b/dist/box.json
index 5f7827e..0317668 100644
--- a/dist/box.json
+++ b/dist/box.json
@@ -5,6 +5,10 @@
             "in": "",
             "name": "autoload.php"
         },
+        {
+            "in": "",
+            "name": "autoload-php7.php"
+        },
         {
             "in": "src",
             "name": "*.php"

```

**Comment by paragonie-security** [comment]
Good catch. We'll update this.

**Comment by paragonie-security** [comment]
Fixed in https://github.com/paragonie/sodium_compat/commit/c61c87736eec5fd18504d3f1e422abb9ca80807e which will be in `v1.20.1` when it's ready.
