### ISSUE TITLE
HKDF

### ISSUE THREAD

**Issue by paragonie-security** [paragonie/sodium_compat#161]
https://github.com/jedisct1/libsodium/releases/tag/1.0.19-RELEASE

Libsodium 1.0.9 provids HKDF over SHA256 and SHA512. We should ensure it's available on all relevant PHP versions.

**Comment by paragonie-security** [comment]
We may hold off on this for several reasons.

1. PHP has the `hash_hkdf()` function since PHP 7.1.0.
2. PHP 8.4's version of ext-sodium does not include the HKDF wrapper functions, so we wouldn't be "compat" by providing it.

Unless @jedisct1 objects, I'm going to punt on this one for now.

**Comment by jedisct1** [comment]
Yup, that doesn't feel necessary.
