### ISSUE TITLE
Missing file using composer install

### ISSUE THREAD

**Issue by Cvar1984** [paragonie/sodium_compat#163]
when i install and run humbug/box build this happen
`paragonie/sodium_compat/autoload-php7.php: Failed to open stream`
so i add manually the autoloader-php7 and it won't stop
`paragonie/sodium_compat/src/Compat.php : Failed to open stream`
so i decide to take a look and its kinda empty in `vendor/paragonie/sodium_compat/`
only
`autoload.php  composer.json  LICENSE`
available
so i think this must be something wrong with installing from the composer and also this issue never happens before from any version available

#159

**Comment by paragonie-security** [comment]
This file is found right here: https://github.com/paragonie/sodium_compat/blob/master/autoload-php7.php

The humbug/box stuff is for packaging a .phar for people that don't want to use Composer. That's all. Use a prebuilt .phar from us or just composer install the requirement.

**Comment by Cvar1984** [comment]
> This file is found right here: https://github.com/paragonie/sodium_compat/blob/master/autoload-php7.php
> 
> The humbug/box stuff is for packaging a .phar for people that don't want to use Composer. That's all. Use a prebuilt .phar from us or just composer install the requirement.

phar is working but using composer install didn't work its only install autoload.php composer.json and LICENSE into vendor directory

**Comment by Cvar1984** [comment]
https://github.com/box-project/box/issues/1010
