### ISSUE TITLE
You know "Salt"?

### ISSUE THREAD

**Issue by rugk** [paragonie/sodium_compat#17]
Do you know https://github.com/devi/Salt?

Please tell me how horrible it is if you think so.
Apart from that (which you would have done anyway, even if I had not requested this) you might (re)use some code from there or might suggest all users to switch to your lib (when it is finished).
In any case I wanted to make you aware of this lib.

**Comment by paragonie-scott** [comment]
Salt seems fine, except:

1. They don't transparently fall back to the PHP extension if it's available.
2. They use multiple classes in a single file.
3. They don't include a lot of nice libsodium APIs e.g. `crypto_sign_detached()` and `crypto_box_seal()`.
4. They're not on Packagist.

**Comment by rugk** [comment]
And…

5. [this](https://github.com/devi/Salt/issues/4)

Anyway I think it is not so good. It seems to be quite unmaintained…

**Comment by paragonie-scott** [comment]
Right, I don't think there's much maintenance going into Salt. If it's ok with you, I'm going to close this issue. :)
