### ISSUE TITLE
Version 0.3.0 (Code Freeze)

### ISSUE THREAD

**Issue by paragonie-scott** [paragonie/sodium_compat#19]
Friday, I'm tagging v0.3.0 (whether or not it's the same code as v0.2.2 remains to be seen). From that point until sodium_compat is audited, I'm enacting a code freeze, which will end once #8 has moved forward at all.

**Comment by Furgas** [comment]
Please include commit 5ed507e in this tag.

**Comment by paragonie-scott** [comment]
Anything in dev-master will be included in the tag.
