### ISSUE TITLE
Resource Leaks in File.php

### ISSUE THREAD

**Issue by defuse** [paragonie/sodium_compat#32]
When this branch is taken, `$ifp` is left open: https://github.com/paragonie/sodium_compat/blob/master/src/File.php#L57. A similar happens if somehow `!is_int($size)` is true even though the file opened successfully. The other functions in `File.php` might have similar leaks (I didn't look).

**Comment by paragonie-scott** [comment]
In https://github.com/paragonie/sodium_compat/commit/1fad40d457ad94c6f8090d496bd94f700cf00571 I move a lot of the exceptions above the type checks and closed `$ifp` if `$ofp` failed to open.

**Comment by paragonie-scott** [comment]
I believe this is fixed as of 0.6.0 but please do let me know if I missed anything.

Thanks @defuse!
