### ISSUE TITLE
PHP 5.2 compatibility

### ISSUE THREAD

**Issue by TobiasBg** [paragonie/sodium_compat#35]
Hi!

To be honest, I didn't try it, but as the lib (at least tentatively) supports 5.2(.4?), it should not be using the `__DIR__` constant in the main autoloader. That magic constant only exists in PHP 5.3+, and should probably be replaced there with e.g. `dirname( __FILE__ )`.

Regards,
Tobias

**Comment by paragonie-scott** [comment]
This will be fixed in v1.0.2
