### ISSUE TITLE
ChaCha20 Poly1305 IETF decrypt fails with Invalid MAC (works on libsodium native)

### ISSUE THREAD

**Issue by paresy** [paragonie/sodium_compat#37]
This test works fine while using the libsodium extension, but fails with your awesome compat library.

```
//SessioKey
$sessionKey = hex2bin("846394900c6c826431361885cfbedf4ec77c44f3022b13e9a7d0200728f0a0e1");

//Encrypted
$encrypted = hex2bin("0ffb01f94450b6803ab9fa5994d4e6242c04ac312c8aae2c8de0effd54a0db9a867ee101bfc5ebb235d734edba3c27f299d81644c1bc7b6ca4802550c29d7b28f10e5f5721bcbad2330337b2b64072fb1ead0de5d4923568c6bae5d1cd6ac528ab4d9fda97fa612ffcac0ad68f79b1578b4f1ea1d241b49aff3c71ca0a6e1c1ede16903136baa3f1c4e38e6e021a697a5fd5fd4f7df199b54c6c");

//Decrypted
$decrypted = sodium_crypto_aead_chacha20poly1305_ietf_decrypt($encrypted, "", "\0\0\0\0PS-Msg05", $sessionKey);

//Encrypt and verify with test data
$reEncrypted = sodium_crypto_aead_chacha20poly1305_ietf_encrypt($decrypted, "", "\0\0\0\0PS-Msg05", $sessionKey);

if($encrypted == $reEncrypted) {
	echo "OK";
} else {
	echo "FAILED";
}
```

**Comment by paragonie-scott** [comment]
That's interesting. I'm not having any luck reproducing a failure, so I've committed a test case. Hopefully, if there is a bug, Travis CI will find it. https://github.com/paragonie/sodium_compat/commit/74d052857c7478f6f790e90f44cd6ce997f2debe

**Comment by paresy** [comment]
I am sorry. I forget to give more information. I am using the following PHP version:  

php-5.6.30-Win32-VC11-x64

**Comment by paragonie-scott** [comment]
Looks like there are some outstanding issues with 32-bit integers, which the rest of the world no longer uses (PHP 7+ on Windows or PHP >= 5.6 on Linux). This is going to be a fun fix.

**Comment by paragonie-scott** [comment]
I've opened #38 to deal with the bigger issue.

In the meantime, if you upgrade to 7.0, then you'll be able to solve this problem immediately.

```
D:\temp\sodium_compat>\php\7.0-x64\php.exe vendor\phpunit\phpunit\phpunit
PHPUnit 5.7.20 by Sebastian Bergmann and contributors.

...............................................................  63 / 121 ( 52%)
.........SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS      121 / 121 (100%)

Time: 1.02 minutes, Memory: 22.00MB

OK, but incomplete, skipped, or risky tests!
Tests: 121, Assertions: 782, Skipped: 49.
```

**Comment by paresy** [comment]
Thanks for verifying! Unfortunately i need to stick to PHP 5.6 at the moment. (Though I am eagerly following the current ext/sodium merge/licensing discussion for PHP 7.2...)

If think we can close this bug in favor of #38 .

Thanks again!
