### ISSUE TITLE
Library does not work with 32-bit integers

### ISSUE THREAD

**Issue by paragonie-scott** [paragonie/sodium_compat#38]
A more general issue than #37 

```PHPUnit 5.7.20 by Sebastian Bergmann and contributors.

F.F.FF..EFFEEFFFE..E....FFF.FFFF.........EFEFFFF.FF.SFF.....FS.  63 / 121 ( 52%)
.S.F.FFF.SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS      121 / 121 (100%)

Time: 27.48 seconds, Memory: 27.00MB

[snip]

ERRORS!
Tests: 121, Assertions: 674, Errors: 7, Failures: 30, Skipped: 52.
```
Here's the full output for the curious.
[output.txt](https://github.com/paragonie/sodium_compat/files/1124921/output.txt)

**Comment by paragonie-scott** [comment]
This is going to require a significant rewrite of a lot of the code, and may not be worth it.

Most systems support 64-bit integers (i.e. `PHP_INT_SIZE === 8`). Windows on PHP 5 is the notable exception here.

For the moment, I'm going to document this behavior and make it fail hard if `PHP_INT_SIZE === 4`. Adding 32-bit implementations for Windows users can come in a future release.

**Comment by paresy** [comment]
At least PHP 5.6 on ARM (like Raspberry Pi) are also effected. (PHP_INT_SIZE is 4)

**Comment by paragonie-scott** [comment]
Thanks for the update. I'll try to prioritize getting 32-bit working, but I've got a lot on my plate.

**Comment by paresy** [comment]
No hurry. I think i found the bug for my PHP 7.x problem and will be able to use native support in 7.2.
