### ISSUE TITLE
Reminder to remove explicit OS constraint on Travis upgrade

### ISSUE THREAD

**Issue by aidantwoods** [paragonie/sodium_compat#44]
As mentioned in #43 opting in early fixes HHVM, but once Travis pushes `trusty` as default then we won't need explicit dependence, so we should remove so that it isn't confusing in future.

More info here: https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming.

This issue should be closable by end of August.

**Comment by paragonie-scott** [comment]
https://blog.travis-ci.com/2017-08-31-trusty-as-default-status

It's technically closable tomorrow, but I'm going to go ahead and commit the change as part of the v1.2 release.
