### ISSUE TITLE
Performance issue between v0.3.1 and v0.4.0

### ISSUE THREAD

**Issue by Wazabiii** [paragonie/sodium_compat#45]
Hello,
I've used the v0.3.1 in a test php 5.4 project (only with crypto_box).

I've notice that the librairy was verry speed (~150ms / 200ms in my personal case)

I've try recently an update to the latest version v1.1.0, but my request time increase a lot (~3.5s / 4s)

I found this speed issue between v0.3.1 and v0.4.0.

It's just to report my use case. Maybe I don't use the lib correctly!

Thanks in advance.

**Comment by paragonie-scott** [comment]
This is documented in the README: https://github.com/paragonie/sodium_compat#help-sodium_compat-is-slow-how-can-i-make-it-fast

**Comment by Wazabiii** [comment]
Sorry, I missed this one!
Thanks a lot, I'll try that.
