### ISSUE TITLE
Call to undefined function Sodium\crypto_sign_ed25519_sk_to_curve25519()

### ISSUE THREAD

**Issue by karek314** [paragonie/sodium_compat#48]
Call to undefined function Sodium\crypto_sign_ed25519_sk_to_curve25519()

Isn't that covered ?

**Comment by paragonie-scott** [comment]
It should be? Let me check, and if it's not, I'll make sure it lands in 1.2.0.

**Comment by karek314** [comment]
Actually, i did used libsodium now directly without sodium_compat.

 sodium_crypto_sign_ed25519_sk_to_curve25519 - worked,

But i did also noticed that overall speed of execution is at least x5 faster without **sodium_compat**, why is that? why should i keep using sodium_compat and not directly libsodium via libsodium-php ?

**Comment by paragonie-scott** [comment]
Well, sodium_compat is a polyfill. If you have the extension, you don't need it.

The purpose is so you can use the sodium features and, if someone for whatever reason doesn't have it installed, your code doesn't break. Sodium_compat is necessarily slower than the extension written in C.

**Comment by karek314** [comment]
Oh i see, i haven't researched it much. Good to know. I definitely see use case for that. Anyway, looking forward to crypto_sign_ed25519_sk_to_curve25519 && crypto_sign_ed25519_pk_to_curve25519.
I will mark this as resolved then.
