### ISSUE TITLE
sodium_crypto_sign_open can also return false

### ISSUE THREAD

**Issue by fkooman** [paragonie/sodium_compat#49]
https://github.com/paragonie/sodium_compat/blob/110b1707f45e3b59311bb488b3af7251673de9b7/lib/php72compat.php#L496

See https://github.com/php/php-src/blob/2aad680c80b568d36d258e1754ca48f6d495360c/ext/sodium/libsodium.c#L1542

**Comment by aidantwoods** [comment]
Also, https://github.com/paragonie/sodium_compat/blob/110b1707f45e3b59311bb488b3af7251673de9b7/lib/php72compat.php#L241

Related: https://github.com/paragonie/pecl-libsodium-doc/pull/12

**Comment by paragonie-scott** [comment]
Yeah, the compat APIs are going to need to be API-consistent, but `ParagonIE_Sodium_Compat` will continue to return a string OR throw an exception. I'll do this in `v1.3.0`.

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/sodium_compat/blob/6ccb221862932409c3f67522a1c153d7e858de3a/lib/php72compat.php#L238-L252

This will fixed in version 1.3.0.
