### ISSUE TITLE
Call to undefined function sodium_crypto_secretbox_keygen()

### ISSUE THREAD

**Issue by Nur777** [paragonie/sodium_compat#52]
Hello to all!

> Call to undefined function sodium_crypto_secretbox_keygen()

I didn't find this function when search this text on Sodium package. But another functions from `_secretbox` exists in Sodium package:
- sodium_crypto_secretbox
- sodium_crypto_secretbox_open

How to generate secret key for sodium_crypto_secretbox if sodium_crypto_secretbox_keygen() function does not exist?
 

P.S. I found that this code could be the solution, but is this solution safe enough?
`$secret_key = random_bytes(SODIUM_CRYPTO_SECRETBOX_KEYBYTES);` 
@paragonie-scott

**Comment by paragonie-scott** [comment]
Yes, `random_bytes()` is exactly what you want.

Forgive the oversight. I'll get these in 1.4.0, due to be released on or before November 30 (PHP 7.2 release date).

**Comment by Nur777** [comment]
Thanks a lot!

**Comment by paragonie-scott** [comment]
The unit tests are still running, but it should be fixed in https://github.com/paragonie/sodium_compat/commit/8843e0d03de12c1ac90675d124c069b8842ca87f which will be included in `v1.4.0`. If any tests fail, I'll fix it tonight.
