### ISSUE TITLE
64-bit format codes are not available for 32-bit versions of PHP

### ISSUE THREAD

**Issue by tuupola** [paragonie/sodium_compat#60]
A [recent change](https://github.com/paragonie/sodium_compat/commit/15cfc2a2a99a153a8b84ebc5b930618c4f442d4b) causes some issues with 32-bit versions of PHP 7. This affects at least calls to `Compat::crypto_aead_xchacha20poly1305_ietf_encrypt()`. 

```text
pack(): 64-bit format codes are not available for 32-bit versions of PHP
```

Code [causing the error](https://github.com/paragonie/sodium_compat/blob/master/src/Core/Util.php#L654-L658) assumes PHP 7 is  always 64bit. For more info see also https://github.com/tuupola/branca-php/issues/2.

**Comment by paragonie-scott** [comment]
That's strange. It should be using Crypto32/Core32 instead of Crypto/Core on 32-bit OSes.

**Comment by paragonie-scott** [comment]
Oh, I see what's happening. I'll get a fix out soon.

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/sodium_compat/releases/tag/v1.5.6
