### ISSUE TITLE
SODIUM_CRYPTO_KX_BYTES vs SODIUM_CRYPTO_KX_SEEDBYTES

### ISSUE THREAD

**Issue by jrfnl** [paragonie/sodium_compat#64]
Just came across a potential inconsistency between this library and the PHP native implementation.

In the PHP native implementation, there is a constant called `SODIUM_CRYPTO_KX_SEEDBYTES`.
https://github.com/php/php-src/blob/397d40cdd7830add08e382c2e8f187b37b55f180/ext/sodium/libsodium.c#L507

I cannot find that constant in this library, but I can find the `SODIUM_CRYPTO_KX_BYTES` constant which does not seem to exist in PHP itself.
https://github.com/paragonie/sodium_compat/blob/3b62b53928638ebc9ee4c50ebb53147547d91c7d/lib/constants.php#L27

Just thought I'd ask about it.

**Comment by paragonie-scott** [comment]
Mere oversight. I'll fix this ASAP.

**Comment by jrfnl** [comment]
@paragonie-scott Thanks. Glad I reported it in that case ;-)

**Comment by paragonie-scott** [comment]
Fixed and released in `v1.6.1`.

**Comment by jrfnl** [comment]
Thank you!
