### ISSUE TITLE
Wrong sodium-compat.phar.sig file in release 1.6.0

### ISSUE THREAD

**Issue by elingerojo** [paragonie/sodium_compat#67]
**wrong sodium-compat.phar.sig file in release 1.6.0** [on here](https://github.com/paragonie/sodium_compat/releases)

`sodium-compat.phar.sig` file in release 1.6.0 is **identical** to release 1.5.6

## Release 1.6.0
``` 
gpg --verify sodium-compat.phar.sig sodium-compat.phar
```

```
gpg: Signature made Tue Jan 30 07:21:23 2018 CST using RSA key ID 826404DA
gpg: BAD signature from "Security <security@paragonie.com>"
```

## Release 1.5.6
``` 
gpg --verify sodium-compat.phar.sig sodium-compat.phar
```

```
gpg: Signature made Tue Jan 30 07:21:23 2018 CST using RSA key ID 826404DA
gpg: Good signature from "Security <security@paragonie.com>"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 7F52 D5C6 1D12 55C7 3136  2E82 6B97 A1C2 8264 04DA
```
---
It looks like the file `sodium-compat.phar.sig` in release 1.5.6 got copied to release 1.6.0 by mistake [on here](https://github.com/paragonie/sodium_compat/releases) (...so it does not work for 1.6.0 gpg verification)

**Comment by paragonie-scott** [comment]
Interesting! I wonder how that happened.

I'll re-sign it and reupload it. I assume 1.6.1 is sane?

**Comment by elingerojo** [comment]
Well ... as a matter of fact 1.6.1 does not have phar files (both are missing). Only the tarball file is present at release tarball page.


________________________________

**Comment by aidantwoods** [comment]
@paragonie-scott when you create a tag for a new release it should trigger a travis build with the tag in `$TRAVIS_TAG` – so you could probably put some sanity checks in that tag build (like downloading the release `.phar` and checking the signature matches). If you push the tag before doing a release on GitHub then that'll probably complicate things though...

**Comment by aidantwoods** [comment]
The v1.5.6 phar was downloaded 6 times :)
https://api.github.com/repos/paragonie/sodium_compat/releases
