### ISSUE TITLE
Fallback not being detected

### ISSUE THREAD

**Issue by martinml** [paragonie/sodium_compat#68]
I'm trying to create code that will have to work in at least PHP 7.0 and work even if `libsodium` is not installed but if it's installed it should fallback to it, for speed.

My problem is that `sodium_compat` doesn't seem to detect the fallback correctly in my environment:
* Ubuntu 16.04 LTS.
* PHP 7.0 from default repos.
* `libsodium-dev` from default repos.
* `libsodium-php` installed with `pecl install libsodium`.
* `sodium_compat` 1.6.1 installed with composer.

 I made a little test script that should explain what I'm seeing:
```php
<?php

require __DIR__ . '/vendor/autoload.php';

var_dump(PHP_INT_SIZE);
var_dump(PHP_VERSION);
var_dump(SODIUM_LIBRARY_MAJOR_VERSION);
var_dump(SODIUM_LIBRARY_MINOR_VERSION);
var_dump(SODIUM_LIBRARY_VERSION);
var_dump(phpversion('sodium'));
var_dump(extension_loaded('sodium'));
var_dump(extension_loaded('libsodium'));

$t = microtime(true);
sodium_crypto_generichash(str_pad('', 4*1024));
echo round(1000*(microtime(true) - $t), 2) . 'ms' . PHP_EOL;

$t = microtime(true);
\ParagonIE_Sodium_Compat::crypto_generichash(str_pad('', 4*1024));
echo round(1000*(microtime(true) - $t), 2) . 'ms' . PHP_EOL;
```

The result:
```
$ php test.php
int(8)
string(23) "7.0.28-0ubuntu0.16.04.1"
int(9)
int(1)
string(5) "1.0.8"
string(6) "2.0.10"
bool(true)
bool(false)
string(64) "b706eb2b5f1abc922d98b722aef70611316fe50d3e3236376ddbe7ed3500b00f"
0.07ms
string(64) "b706eb2b5f1abc922d98b722aef70611316fe50d3e3236376ddbe7ed3500b00f"
34.5ms
```

**Comment by paragonie-scott** [comment]
This might be due to function call overhead.

What does `ParagonIE_Sodium_Compat::use_fallback('crypto_generichash')` return? (You'll need to edit this file and make the method `public`.)

**Comment by paragonie-scott** [comment]
```php
class Shim extends ParagonIE_Sodium_Compat
{
    public static function fallback($arg)
    {
        return self::use_fallback($arg);
    }
}

var_dump(Shim::fallback('crypto_generichash'));
```

**Comment by paragonie-scott** [comment]
Can you pull the `fix-compat-fallback` branch and tell me if this fixes the problem for you?
