### ISSUE TITLE
Experiment: Amputate 32-bit Windows BigInt implementations?

### ISSUE THREAD

**Issue by paragonie-scott** [paragonie/sodium_compat#77]
Right now our Int32 class consists of 2 limbs and our Int64 class consists of 4 limbs, each 16 bits.

While this is simple to reason about, it might be worth investigating a reduced-limb implementation of, at least, Int64. (I don't think Int32 can be expressed in fewer than two limbs.)

Benefits:
* Less additions, etc.
* Less memory usage.
* More speed.

Downsides:
* Harder-to-audit/read code

### Current Picture

Here's what the current implementation looks like (hex then binary):

```
[0]      [1]      [2]      [3]      
0000FFFF 0000FFFF 0000FFFF 0000FFFF 

[0]
00000000 00000000 11111111 11111111
[1]
00000000 00000000 11111111 11111111
[2]
00000000 00000000 11111111 11111111
[3]
00000000 00000000 11111111 11111111
```

Because PHP's integers are signed, we want to avoid the most significant bit.

A naive optimization that would save us from one limb looks like this:

```
[0]      [1]      [2]     
0000FFFF 00FFFFFF 00FFFFF

[0]
00000000 00000000 11111111 11111111
[1]
00000000 11111111 11111111 11111111
[2]
00000000 11111111 11111111 11111111
```

This would save us roughly 25% of memory usage, and make most operations 25% faster. I'd need to benchmark this to be exact.

I'm writing my thoughts here to solicit feedback before I embark on such an initiative. Note: It might be wiser to just add a GMP implementation.

**Comment by defuse** [comment]
The current implementation is easy to understand even if a bit wasteful, are actual users running into performance problems (and can't get actual libsodium)?

**Comment by paragonie-scott** [comment]
Yes. See #75

**Comment by paragonie-scott** [comment]
#78 greatly reduced any benefit this might have. I'll revisit this in the future, barring any higher priorities.
