### ISSUE TITLE
Use of undefined constant SODIUM_LIBRARY_MAJOR_VERSION - assumed 'SODIUM_LIBRARY_MAJOR_VERSION

### ISSUE THREAD

**Issue by eaponiente** [paragonie/sodium_compat#81]
PHP: 7.1
Ubuntu: 14.04

followed all the instructions in the website and last part was put `sodium.so` in my 
`/etc/php/fpm/php.ini`.

now to test it out, I tried the ff code in `php artisan tinker`(ran in command line) inside one of my laravel projects

```
var_dump([
    SODIUM_LIBRARY_MAJOR_VERSION,
    SODIUM_LIBRARY_MINOR_VERSION,
    SODIUM_LIBRARY_VERSION
]);
```
and got this results 
```
array(2) {
  [0] =>
  int(9)
  [1] =>
  int(1)
  [2] =>
  string(6) "1.0.14"
}
```

Now, when I tried the code on my browser.

I am getting this error `Use of undefined constant SODIUM_LIBRARY_MAJOR_VERSION - assumed 'SODIUM_LIBRARY_MAJOR_VERSION`

**Comment by paragonie-scott** [comment]
If you're looking to fix your PECL configuration, there's not much help I can offer.

But if you wanted the polyfill to include these constants, it does in 1.8.0.
