### ISSUE TITLE
Weird classes thrown

### ISSUE THREAD

**Issue by szepeviktor** [paragonie/sodium_compat#88]
I'm doing static analysis.

Could you help me fix thrown types in code vs. in PHPDoc?

https://github.com/paragonie/sodium_compat/blob/master/lib/sodium_compat.php#L41-L60

**Comment by szepeviktor** [comment]
There is no Sodium\Error nor Sodium\Exception.

**Comment by paragonie-scott** [comment]
It's `\SodiumException`, not `Sodium\Exception`.

**Comment by paragonie-scott** [comment]
If you're curious about the explicit `\` prefix: https://github.com/UnderhandedCrypto/entries/blob/master/2014/submissions/ScottArcizewski/email-exerpt.txt

**Comment by szepeviktor** [comment]
Okay. Thank you.

I remove `@throw` where it is really **catched**.
